### PR TITLE
Added ui-router support. Fixes #1

### LINKED ISSUE #1: Support for UI-Router

### PR DESCRIPTION
**Pull request by lee-40square**
Simple solution to add ui-router support. Resolves issue #1.

### CODE REVIEW

**Comment by lee-40square** [comment]
Actually, I was thinking that this PR is kinda shit. Would be better if there was a switch that could be set to choose between ui-router or ngRoute. The way it is now it assumes that if it isn't ngRoute it's ui-router which is kinda a hack. Let me fix this and push an update.

**Comment by AvraamMavridis** [comment]
Hey, Lee. Yeah a switch will be better. Thx for the contribution. I suggest ngRoute as default.

**Comment by lee-40square** [comment]
I'm working on a better solution that uses the $injector.has() method but running into a scope problem at the moment. I probably won't be able to get back to this until next week. So far try/catch is the best solution. A wrapper solution would be really nice but not sure it's worth the effort.

**Comment by AvraamMavridis** [comment]
I will merge this PR, since is good enough. And I will take a look when I have time for a wrapper solution. Thx.

**Pull request merged**
